# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-22 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proscenium', '0002_auto_20180607_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='country',
        ),
        migrations.RemoveField(
            model_name='system',
            name='country',
        ),
        migrations.AddField(
            model_name='area',
            name='area_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proscenium.Country'),
        ),
        migrations.AddField(
            model_name='area',
            name='area_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proscenium.System'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proscenium.System'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proscenium.System'),
        ),
    ]
